////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ARRAYS AND MOCK DATA //

// name arrays
export const firstNames = [
	"Adam",
	"Andre",
	"Jasmine",
	"Madhur",
	"Chris",
	"Paulo",
	"Mike",
	"Kush",
	"Lionel",
	"Cristiano",
];

export const lastNames = [
	"Pangelinan",
	"Hanna",
	"Kobata",
	"Luthra",
	"Cheasty",
	"Bocanegra",
	"Madsen",
	"Patel",
	"Messi",
	"Ronaldo",
];

export const userNames = [
	"BUBBAPANG",
	"andre3000",
	"bachataforlife",
	"alpacaboi",
	"itsbritneybeach",
	"blackmouth",
	"imalaketaHOE",
	"gotthatgoodgood",
	"goatmeal",
	"siiiuuu7",
];

// init needs array
export const needs = [
	"transcendence",
	"actualization",
	"aesthetics",
	"understanding",
	"esteem",
	"love",
	"safety",
	"physiological",
];

// mock highlight and lowlight data
export const mockHighlights = [
	"Had a productive day at work.",
	"Spent quality time with family.",
	"Finished reading a great book.",
	"Went for a long walk.",
	"Completed a challenging workout.",
	"Had an insightful conversation with a friend.",
	"Made progress on a personal project.",
	"Cooked a delicious meal.",
	"Helped a friend with a problem.",
	"Learned a new skill.",
	"Received positive feedback at work.",
	"Made a new connection.",
	"Volunteered for a good cause.",
	"Completed a home improvement project.",
	"Took time for self-care.",
	"Listened to an inspiring podcast.",
	"Attended an interesting event.",
	"Traveled to a new place.",
	"Received a compliment.",
	"Watched a fascinating documentary.",
	"Achieved a personal goal.",
	"Solved a complex problem.",
	"Went on a fun outing with friends.",
	"Made progress in learning a new language.",
	"Enjoyed a beautiful sunset.",
	"Wrote a thoughtful letter.",
	"Had a breakthrough idea.",
	"Tried a new recipe and loved it.",
	"Received a thoughtful gift.",
	"Made someone smile.",
	"Felt a sense of accomplishment.",
	"Reconnected with an old friend.",
	"Took a relaxing bath.",
	"Finished a creative project.",
	"Got a promotion at work.",
	"Went to a fun social event.",
	"Played a new sport.",
	"Watched a great movie.",
	"Took a spontaneous trip.",
	"Overcame a fear.",
	"Completed a difficult task.",
	"Meditated and felt at peace.",
	"Had a memorable dream.",
	"Discovered a new hobby.",
	"Donated to a charity.",
	"Went to a live performance.",
	"Read an interesting article.",
	"Enjoyed a fun game night.",
	"Gave a successful presentation.",
	"Felt inspired by someone's story.",
	"Had a productive day at work.",
	"Spent quality time with family.",
	"Finished reading a great book.",
	"Went for a long walk.",
	"Completed a challenging workout.",
	"Had an insightful conversation with a friend.",
	"Made progress on a personal project.",
	"Had a productive day at work.",
	"Spent quality time with family.",
	"Finished reading a great book.",
	"Went for a long walk.",
	"Completed a challenging workout.",
	"Had an insightful conversation with a friend.",
	"Made progress on a personal project.",
	"Cooked a delicious meal.",
	"Helped a friend with a problem.",
	"Learned a new skill.",
	"Received positive feedback at work.",
	"Made a new connection.",
	"Volunteered for a good cause.",
	"Completed a home improvement project.",
	"Took time for self-care.",
	"Listened to an inspiring podcast.",
];

export const mockLowlights = [
	"Had a disagreement with a colleague.",
	"Missed an important deadline.",
	"Felt overwhelmed by tasks.",
	"Struggled with time management.",
	"Procrastinated on a project.",
	"Skipped a workout session.",
	"Had difficulty sleeping.",
	"Had a disagreement with a colleague.",
	"Missed an important deadline.",
	"Felt overwhelmed by tasks.",
	"Struggled with time management.",
	"Procrastinated on a project.",
	"Skipped a workout session.",
	"Had difficulty sleeping.",
	"Faced a challenging personal issue.",
	"Dealt with a frustrating situation.",
	"Lost track of time on social media.",
	"Felt stressed about upcoming events.",
	"Had trouble focusing on work.",
	"Didn't stick to a healthy diet.",
	"Missed an appointment.",
	"Struggled with motivation.",
	"Faced a setback on a personal goal.",
	"Had a disagreement with a colleague.",
	"Missed an important deadline.",
	"Felt overwhelmed by tasks.",
	"Struggled with time management.",
	"Procrastinated on a project.",
	"Skipped a workout session.",
	"Had difficulty sleeping.",
	"Faced a challenging personal issue.",
	"Dealt with a frustrating situation.",
	"Lost track of time on social media.",
	"Felt stressed about upcoming events.",
	"Had trouble focusing on work.",
	"Didn't stick to a healthy diet.",
	"Missed an appointment.",
	"Struggled with motivation.",
	"Faced a setback on a personal goal.",
	"Encountered an unexpected obstacle.",
	"Experienced a loss.",
	"Got caught in bad weather.",
	"Felt discouraged by a lack of progress.",
	"Lost an important item.",
	"Argued with a family member.",
	"Had a disappointing experience.",
	"Felt lonely or isolated.",
	"Made a mistake at work.",
	"Struggled to find a solution.",
	"Felt unwell.",
	"Received negative feedback.",
	"Had a misunderstanding with someone.",
	"Missed an opportunity.",
	"Felt let down by someone.",
	"Faced a financial challenge.",
	"Experienced a delay or cancellation.",
	"Had to cancel plans.",
	"Struggled with a personal relationship.",
	"Felt anxious or worried.",
	"Encountered a technical issue.",
	"Felt underappreciated.",
];

// mock suggestions data with body and category tags
export const mockSuggestions = [
	{
		body: "To improve your sense of safety, try to surround yourself with positive and supportive people.",
		categoryTag: "Safety",
	},
	{
		body: "To increase your self-esteem, practice positive affirmations and focus on your accomplishments.",
		categoryTag: "Esteem",
	},
	{
		body: "To enhance your love and relationships, work on your communication skills and express your feelings openly.",
		categoryTag: "Love",
	},
	{
		body: "To boost your knowledge, try to read at least one book per month in various fields.",
		categoryTag: "Knowledge",
	},
	{
		body: "To improve your aesthetics, explore new forms of art and try to incorporate them into your daily life.",
		categoryTag: "Aesthetics",
	},
	{
		body: "To work on your actualization, set clear goals for yourself and regularly review your progress.",
		categoryTag: "Actualization",
	},
	{
		body: "To achieve transcendence, practice mindfulness and meditation to connect with your inner self.",
		categoryTag: "Transcendence",
	},
	{
		body: "For better physiological well-being, maintain a balanced diet and exercise regularly.",
		categoryTag: "Physiological",
	},
];